#!/bin/sh

### BEGIN INIT INFO
# Provides: pure-ftpd
# Required-Start: $all
# Required-Stop: $all
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: starts pure-ftpd server
# Description: starts pure-ftpd server
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=pure-ftpd
DESC="ftp server"
WRAPPER=/usr/sbin/pure-ftpd
CONFIG=/etc/pure-ftpd-db.conf

# load LSB init-functions to get status_of_proc helper
. /lib/lsb/init-functions

PIDFILE=/var/run/pure-ftpd.pid
DAEMON=/usr/sbin/pure-ftpd

#set -e

case "$1" in
  start)
	echo -n "try start"
        echo -n "Starting $DESC: "
        start-stop-daemon --start --pidfile "$PIDFILE" --exec $WRAPPER -- -l mysql:$CONFIG -B
	netstat -tnulp | grep pure-ftpd
        ;;
  stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --oknodo --pidfile "$PIDFILE"
        echo "$NAME."
        ;;
  restart|force-reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon --stop --oknodo --pidfile "$PIDFILE"
        sleep 1
        start-stop-daemon --start --pidfile "$PIDFILE" --exec $WRAPPER
        ;;
  status)
        status_of_proc -p /var/run/pure-ftpd.pid $DAEMON $NAME && exit 0 || exit $?
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "ZZ Usage: $N {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0
